version: "3.8"

services:
  db:
    image: postgres:15
    container_name: mdp_register_user
    restart: always
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: felipe
      POSTGRES_PASSWORD: 1234
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata_register:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U felipe"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata_register:


# cd /mnt/c/Codigo_melhorados/e-commerce-microservice/Register-Service/src/main/java/br/com/e_commerce/register_service/config
# docker compose -p register up -d
# docker exec -it mdp_register_user psql -U felipe -d postgres -c "DROP DATABASE IF EXISTS user;"